import type { AgentProfile, SkillAuditEvent, SkillRegistryItem } from "./api";

/**
 * Dev-only mock data for the Skill Hub view so the layout can be reviewed without a live BFF.
 * These records are passed through the existing `normalize*` helpers, so only the meaningful
 * fields are filled here; defaults are filled by the normalizers.
 */

const now = Date.now();
const day = 86_400_000;

/** Raw skill records; normalized by `normalizeSkillRegistryItem` before use. Typed as unknown so
 *  partial records (e.g. the deprecated flag) pass straight into the normalizer. */
export const mockSkills: unknown[] = [
  {
    id: "code-runner",
    name: "Code Runner",
    summary: "在隔离沙箱中执行多语言代码片段并回传结构化结果。",
    category: "开发工具",
    provider: "Orbit",
    version: "2.1.0",
    runtime: "Node 22 sandbox",
    permissions: ["fs:read", "proc:spawn", "net:loopback"],
    maturity: "stable",
    tags: ["代码", "执行", "沙箱"],
    sourceType: "local",
    registrySource: "official",
    publisher: { id: "orbit", name: "Orbit", verified: true },
    downloads: 4823,
    rating: 4.8,
    packageSha256: "sha256:a1b2c3d4e5f60718293a4b5c6d7e8f90",
    status: "installed",
    installed: true,
    installedVersion: "2.1.0",
    installedAt: now - 12 * day,
    availableVersion: "2.1.0",
    versions: ["2.1.0", "2.0.0", "1.9.4"],
  },
  {
    id: "web-search",
    name: "Web Search",
    summary: "联网检索并提炼多源信息，附带引用来源。",
    category: "信息检索",
    provider: "Orbit",
    version: "1.4.2",
    runtime: "Edge runtime",
    permissions: ["net:fetch"],
    maturity: "stable",
    tags: ["搜索", "检索", "联网"],
    sourceType: "local",
    registrySource: "verified",
    publisher: { id: "orbit", name: "Orbit", verified: true },
    downloads: 9170,
    rating: 4.6,
    packageSha256: "sha256:b2c3d4e5f60718293a4b5c6d7e8f9012",
    status: "updateAvailable",
    installed: true,
    installedVersion: "1.3.0",
    installedAt: now - 30 * day,
    availableVersion: "1.4.2",
    previousInstalledVersion: "1.3.0",
    versions: ["1.4.2", "1.3.0", "1.2.1"],
  },
  {
    id: "pdf-reader",
    name: "PDF Reader",
    summary: "解析长文档、提取章节与表格，支持问答式摘要。",
    category: "文档处理",
    provider: "Community",
    version: "3.0.0",
    runtime: "Local runtime",
    permissions: ["fs:read"],
    maturity: "stable",
    tags: ["pdf", "文档", "摘要"],
    sourceType: "local",
    registrySource: "community",
    publisher: { id: "doc-lab", name: "DocLab", verified: false },
    downloads: 2310,
    rating: 4.2,
    packageSha256: "sha256:c3d4e5f60718293a4b5c6d7e8f901234",
    status: "available",
    installed: false,
    installedVersion: "",
    availableVersion: "3.0.0",
    versions: ["3.0.0", "2.4.1", "2.3.0"],
  },
  {
    id: "sql-query",
    name: "SQL Query",
    summary: "连接本地数据库执行查询并可视化结果集。",
    category: "数据",
    provider: "Community",
    version: "1.2.0",
    runtime: "Local runtime",
    permissions: ["db:read", "net:fetch"],
    maturity: "beta",
    tags: ["sql", "数据库", "分析"],
    sourceType: "local",
    registrySource: "community",
    publisher: { id: "data-craft", name: "DataCraft", verified: false },
    downloads: 1880,
    rating: 4.0,
    packageSha256: "sha256:d4e5f60718293a4b5c6d7e8f90123456",
    status: "available",
    installed: false,
    installedVersion: "",
    availableVersion: "1.2.0",
    versions: ["1.2.0", "1.1.0", "1.0.0"],
  },
  {
    id: "image-gen",
    name: "Image Generator",
    summary: "根据提示词生成与改写图像，支持风格预设。",
    category: "创意",
    provider: "Orbit",
    version: "0.9.1",
    runtime: "Edge runtime",
    permissions: ["net:fetch", "fs:write"],
    maturity: "beta",
    tags: ["图像", "生成", "ai"],
    sourceType: "remote",
    registrySource: "official",
    publisher: { id: "orbit", name: "Orbit", verified: true },
    downloads: 6740,
    rating: 4.5,
    packageSha256: "sha256:e5f60718293a4b5c6d7e8f9012345678",
    status: "installed",
    installed: true,
    installedVersion: "0.9.0",
    installedAt: now - 5 * day,
    availableVersion: "0.9.1",
    previousInstalledVersion: "0.9.0",
    versions: ["0.9.1", "0.9.0", "0.8.3"],
  },
  {
    id: "memory-context",
    name: "Memory Context",
    summary: "为长对话维护结构化记忆与可检索上下文。",
    category: "运行时",
    provider: "Orbit",
    version: "0.8.0",
    runtime: "Local runtime",
    permissions: ["fs:read", "fs:write"],
    maturity: "stable",
    tags: ["记忆", "上下文", "runtime"],
    sourceType: "local",
    registrySource: "local",
    publisher: { id: "orbit", name: "Orbit", verified: true },
    downloads: 3050,
    rating: 4.3,
    packageSha256: "sha256:f60718293a4b5c6d7e8f901234567890",
    status: "installed",
    installed: true,
    installedVersion: "0.8.0",
    installedAt: now - 60 * day,
    availableVersion: "0.8.0",
    versions: ["0.8.0", "0.7.2"],
  },
  {
    id: "quality-gate",
    name: "Quality Gate",
    summary: "在交付前运行静态检查与测试门禁。",
    category: "工程",
    provider: "Orbit",
    version: "0.9.0",
    runtime: "Local runtime",
    permissions: ["proc:spawn", "fs:read"],
    maturity: "stable",
    tags: ["质量", "测试", "门禁"],
    sourceType: "local",
    registrySource: "local",
    publisher: { id: "orbit", name: "Orbit", verified: true },
    downloads: 2710,
    rating: 4.4,
    packageSha256: "sha256:0718293a4b5c6d7e8f90123456789012",
    status: "installed",
    installed: true,
    installedVersion: "0.9.0",
    installedAt: now - 45 * day,
    availableVersion: "0.9.0",
    versions: ["0.9.0", "0.8.1", "0.7.0"],
  },
  {
    id: "private-deploy",
    name: "Private Deployer",
    summary: "私有发布的部署技能，仅团队内部可见。",
    category: "运维",
    provider: "Acme",
    version: "1.0.3",
    runtime: "Local runtime",
    permissions: ["net:fetch", "proc:spawn"],
    maturity: "stable",
    tags: ["部署", "私有", "ops"],
    sourceType: "custom",
    registrySource: "private",
    publisher: { id: "acme", name: "Acme", verified: true },
    downloads: 142,
    rating: 4.1,
    packageSha256: "sha256:18293a4b5c6d7e8f9012345678901234",
    status: "available",
    installed: false,
    installedVersion: "",
    availableVersion: "1.0.3",
    versions: ["1.0.3", "1.0.0"],
  },
  {
    id: "legacy-fmt",
    name: "Legacy Formatter",
    summary: "已弃用的格式化工件，保留仅供回滚。",
    category: "工程",
    provider: "Community",
    version: "0.3.0",
    runtime: "Local runtime",
    permissions: ["fs:write"],
    maturity: "beta",
    tags: ["格式", "legacy"],
    sourceType: "local",
    registrySource: "community",
    publisher: { id: "old-ones", name: "OldOnes", verified: false },
    downloads: 90,
    rating: 3.2,
    packageSha256: "sha256:293a4b5c6d7e8f901234567890123456",
    status: "available",
    installed: false,
    installedVersion: "",
    availableVersion: "0.3.0",
    versions: ["0.3.0", "0.2.0"],
    deprecated: true,
  },
];

/** A couple of mock agents so the "used by" section in the skill detail is populated. */
export const mockSkillAgents: AgentProfile[] = [
  {
    id: "agent-code",
    avatarId: "code",
    name: "代码助手",
    description: "擅长代码生成、调试与技术文档编写。",
    scenario: "编程辅助、代码审查",
    skillIds: ["code-runner", "web-search", "memory-context", "quality-gate"],
    skills: [
      { skillId: "code-runner", version: "2.1.0", sourceType: "local", registrySource: "official" },
      { skillId: "web-search", version: "1.3.0", sourceType: "local", registrySource: "verified" },
      { skillId: "memory-context", version: "0.8.0", sourceType: "local", registrySource: "local" },
      { skillId: "quality-gate", version: "0.9.0", sourceType: "local", registrySource: "local" },
    ],
    actions: ["运行代码片段", "搜索技术文档"],
    systemPrompt: "你是一个专业的编程助手。",
    color: "#3b82f6",
    createdAt: now - 10 * day,
    updatedAt: now - day,
  },
  {
    id: "agent-create",
    avatarId: "bot",
    name: "内容创作",
    description: "面向长文写作与多语言翻译。",
    scenario: "文章撰写、营销文案",
    skillIds: ["pdf-reader", "image-gen"],
    skills: [
      { skillId: "pdf-reader", version: "3.0.0", sourceType: "local", registrySource: "community" },
      { skillId: "image-gen", version: "0.9.0", sourceType: "remote", registrySource: "official" },
    ],
    actions: ["生成大纲"],
    systemPrompt: "你是一个专业的内容创作者。",
    color: "#ec4899",
    createdAt: now - 20 * day,
    updatedAt: now - 2 * day,
  },
];

/** Mock audit trail so the detail "审计日志" section is populated. */
export const mockSkillAuditEvents: SkillAuditEvent[] = [
  { id: "a1", action: "install", ok: true, code: "OK", message: "安装成功", skillId: "code-runner", skillName: "Code Runner", version: "2.1.0", status: "installed", at: now - 12 * day },
  { id: "a2", action: "update", ok: true, code: "OK", message: "升级到 1.4.2", skillId: "web-search", skillName: "Web Search", version: "1.4.2", status: "updateAvailable", at: now - 3 * day },
  { id: "a3", action: "install", ok: true, code: "OK", message: "安装成功", skillId: "image-gen", skillName: "Image Generator", version: "0.9.0", status: "installed", at: now - 5 * day },
  { id: "a4", action: "rollback", ok: true, code: "OK", message: "回滚到 1.3.0", skillId: "web-search", skillName: "Web Search", version: "1.3.0", status: "installed", at: now - 2 * day },
  { id: "a5", action: "uninstall", ok: true, code: "OK", message: "卸载 image-gen 0.8.0", skillId: "image-gen", skillName: "Image Generator", version: "0.8.0", status: "available", at: now - 15 * day },
];
